import type { ExtensionSettingsDefinition } from "./definition.ts";
import { readTextIfPresent, writeTextAtomically } from "./file-system.ts";
import { formatJson } from "./json-value.ts";
import { createPrevalidatedExtensionSettingsArtifact } from "./runtime.ts";
import {
    renderReadmeSettingsSection,
    replaceGeneratedReadmeSection,
    type RenderReadmeOptions,
} from "./settings-documentation.ts";
import { createSettingsFileSchema } from "./schema-document.ts";

export type SettingsArtifactTargets = {
    readonly schemaPath: string;
    readonly readmePath: string;
    readonly prevalidationPath?: string;
    readonly globalPath?: string;
};

export type RenderedSettingsArtifacts = {
    readonly schema: string;
    readonly readmeSection: string;
    readonly prevalidation?: string;
};

export type GeneratedSettingsArtifacts = {
    readonly changedPaths: readonly string[];
};

export type CheckedSettingsArtifacts = {
    readonly current: boolean;
    readonly stalePaths: readonly string[];
};

function readmeRenderOptions(targets: SettingsArtifactTargets): RenderReadmeOptions {
    return targets.globalPath === undefined ? {} : { globalPath: targets.globalPath };
}

function renderPrevalidation(definition: ExtensionSettingsDefinition): string {
    const artifact = createPrevalidatedExtensionSettingsArtifact(definition);
    return [
        "// Generated by pi-extension-settings. Do not edit.",
        `const artifact = ${JSON.stringify(artifact, undefined, 4)} as const;`,
        "",
        "export default artifact;",
        "",
    ].join("\n");
}

export function renderSettingsArtifacts(
    definition: ExtensionSettingsDefinition,
    targets: SettingsArtifactTargets,
): RenderedSettingsArtifacts {
    const rendered = {
        schema: formatJson(createSettingsFileSchema(definition)),
        readmeSection: renderReadmeSettingsSection(definition, readmeRenderOptions(targets)),
    };
    return targets.prevalidationPath === undefined
        ? rendered
        : { ...rendered, prevalidation: renderPrevalidation(definition) };
}

function expectedReadme(readmePath: string, section: string): string {
    const current = readTextIfPresent(readmePath);
    if (current === undefined) {
        throw new Error(`README does not exist: ${readmePath}`);
    }

    const expected = replaceGeneratedReadmeSection(current, section);
    if (expected === undefined) {
        throw new Error(`README generation markers are invalid in ${readmePath}`);
    }
    return expected;
}

export function generateSettingsArtifacts(
    definition: ExtensionSettingsDefinition,
    targets: SettingsArtifactTargets,
): GeneratedSettingsArtifacts {
    const rendered = renderSettingsArtifacts(definition, targets);
    const readme = expectedReadme(targets.readmePath, rendered.readmeSection);

    const changedPaths: string[] = [];
    if (writeTextAtomically(targets.schemaPath, rendered.schema) !== "unchanged") {
        changedPaths.push(targets.schemaPath);
    }
    if (writeTextAtomically(targets.readmePath, readme) !== "unchanged") {
        changedPaths.push(targets.readmePath);
    }
    if (
        targets.prevalidationPath !== undefined &&
        rendered.prevalidation !== undefined &&
        writeTextAtomically(targets.prevalidationPath, rendered.prevalidation) !== "unchanged"
    ) {
        changedPaths.push(targets.prevalidationPath);
    }

    return { changedPaths };
}

export function checkSettingsArtifacts(
    definition: ExtensionSettingsDefinition,
    targets: SettingsArtifactTargets,
): CheckedSettingsArtifacts {
    const rendered = renderSettingsArtifacts(definition, targets);
    const readme = expectedReadme(targets.readmePath, rendered.readmeSection);
    const schemaCurrent = readTextIfPresent(targets.schemaPath);
    const readmeCurrent = readTextIfPresent(targets.readmePath);
    const prevalidationCurrent =
        targets.prevalidationPath === undefined
            ? undefined
            : readTextIfPresent(targets.prevalidationPath);

    const stalePaths: string[] = [];
    if (schemaCurrent !== rendered.schema) stalePaths.push(targets.schemaPath);
    if (readmeCurrent !== readme) stalePaths.push(targets.readmePath);
    if (
        targets.prevalidationPath !== undefined &&
        prevalidationCurrent !== rendered.prevalidation
    ) {
        stalePaths.push(targets.prevalidationPath);
    }

    return { current: stalePaths.length === 0, stalePaths };
}
